apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: AB3-test-cluster
  region: us-east-2

managedNodeGroups:
  - name: ng-worker
    amiFamily: AmazonLinux2
    instanceType: m5.large
    desiredCapacity: 3
    privateNetworking: true
    minSize: 3
    maxSize: 8
iam:
  withOIDC: true
