apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: AB3-test-cluster
  region: us-east-2

managedNodeGroups:
  - name: ng-worker
    instanceType: m5.large
    desiredCapacity: 3
    privateNetworking: true
    
