apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: my-security-group-policy
spec:
  podSelector: 
    matchLabels:
      app: backend
  securityGroups:
    groupIds:
      - sg-08eb7f79c86578931