apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: bankapp-backend
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bankapp-backend
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50