apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bankapp-backend
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bankapp-backend
  targetCPUUtilizationPercentage: 5